Add dpkg platform_userguide_test test to checkbox-oem

diff --git a/contrib/checkbox-oem/checkbox-provider-oem/bin/misc-platform_userguide_test b/contrib/checkbox-oem/checkbox-provider-oem/bin/misc-platform_userguide_test
--- a/contrib/checkbox-oem/checkbox-provider-oem/bin/misc-platform_userguide_test
+++ b/contrib/checkbox-oem/checkbox-provider-oem/bin/misc-platform_userguide_test
@@ -1,8 +1,15 @@
 #!/bin/bash
+
+if [ -z ${SNAP+x} ]; then
+    DPKG_STATUS="/var/lib/dpkg/status";
+else
+    DPKG_STATUS="/var/lib/snapd/hostfs/var/lib/dpkg/status";
+fi
+
 failed()
 {
     >&2 echo "$*"
-    >&2 "$0 failed!"
+    >&2 echo "$0 failed!"
     exit 1
 }
 
@@ -13,17 +20,30 @@ passed()
     exit 0
 }
 
+is_installed() {
+    local pkg=$1
+    # Use awk to treat the file as blocks separated by blank lines
+    awk -v pkg="$pkg" '
+        BEGIN { RS=""; FS="\n" }
+        $1 == "Package: "pkg {
+            if ($0 ~ /Status: install ok installed/) { exit 0 } else { exit 1 }
+        }
+    ' "$DPKG_STATUS"
+}
+
 # Check userguide package if installed in sutton project
 # https://warthogs.atlassian.net/browse/OEX86-301
 check_sutton_userguide() {
     # userguide package will depend on a oem-sutton-common-doc package
-    for pkg in $(dpkg-query -W -f='${Package}\n'  "oem-sutton-*-doc" 2> /dev/null); do
+    local packages=$(grep "^Package: oem-sutton-.*-doc$" "$DPKG_STATUS" | cut -d' ' -f2)
+    for pkg in $packages; do
         platform_name=$(echo "${pkg}" | cut -d'-' -f3)
         if [ "$platform_name" = "common" ]; then
             # Ignore common doc package
             continue
         fi
-        if dpkg-query -W -f='${Status}\n' "${pkg}" 2> /dev/null | grep -q "install ok installed"; then
+
+        if is_installed "${pkg}"; then
             passed "Found the platform userguide package: ${pkg}"
         fi
     done
